main = "./routes/physicists.ts"

compatibility_date = "2025-03-07"

# The rate limiting API is in open beta.

[[unsafe.bindings]]
name = "PLANCK_RATE_LIMITER"
type = "ratelimit"

# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.

namespace_id = "2006"

# Limit: the number of tokens allowed within a given period in a single
# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60

simple = { limit = 100, period = 60 }